import pyqrcode


def qr_code(name=''):

    qr_code = pyqrcode.create(
        name,
    )
    qr_code.svg("qr_code_image.svg", scale=8)
   # qr.png("qr_code_image.png", scale=6)
    print("QR Code Generator")


if __name__ == "__main__":
    qr_code('This QR Code generated By Vikas Ukani')
